# Generated by Django 2.1.2 on 2018-11-13 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='last_upadated',
            new_name='last_updated',
        ),
    ]
